export { default as HeaderSection } from './HeaderSection'
export { default as SkillsSection } from './SkillsSection'
export { default as TechnicSkillSection } from './TechnicSkillSection'
export { default as ToolsSection } from './ToolsSection'
export { default as ContactSection } from './ContactSection'
export { default as AboutMeSection } from './AboutMeSection'